name: AutoShutdown-Bukkit
main: com.x08xnick.shutdown.AutoShutdown
version: 1.1.0
api-version: 1.13
author: x08xnick
description: Shuts down the server after a configurable time of inactivity.
commands:
  asd:
    description: AutoShutdown plugin command.
    usage: /asd reload
    permission: autosd.reload
permissions:
  autosd.reload:
    description: Allows reloading the AutoShutdown config.
    default: op
